### ISSUE TITLE
/monitor endpoint does not work with Spring Cloud Finchley.M9

### ISSUE THREAD

**Issue by anthonyrm** [spring-cloud/spring-cloud-bus#112] opened 2018-04-09 20:34 UTC
Hello, I have created a config server and a config client with SpringBoot 2.0.1.RELEASE and Spring Cloud Finchley.M9. 

I have added spring-cloud-config-monitor to call /monitor endpoint via webhook, however the config client does not refresh the configuration when the webhook is triggered. 
I also have exposed the /actuator/bus-refresh endpoint to make local test and this works perfectly. 

Config Server -> https://github.com/anthonyrm/spring-cloud-config-server
Config Client -> https://github.com/anthonyrm/spring-cloud-config-client
Config Data -> https://github.com/anthonyrm/ConfigData

Notes: 
- I have tested with Finchley.BUILD-SNAPSHOT version and does not work either.
- When I use the Springboot 1.5.10.RELEASE and Spring cloud Edware.SR3 the webhook works perfectly.

**Comment by gs-spadmanabhan** [comment] 2018-04-19 13:39
@spencergibb the dashes in app name is getting added via spring cloud jars (yet to find from where) but here is the logs which I see (even though my app name is just a single word "rickle"). Can you please let us know how to correct this?

018-04-19 19:05:26.227  INFO 67226 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [localhost:5672]
2018-04-19 19:05:26.263  INFO 67226 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Created new connection: rickle#0/SimpleConnection@1bec1589 [delegate=amqp://guest@127.0.0.1:5672/, localPort= 49997]
2018-04-19 19:05:26.312  INFO 67226 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'rickle-1.springCloudBusOutput' has 1 subscriber(s).
2018-04-19 19:05:26.314  INFO 67226 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2018-04-19 19:05:26.315  INFO 67226 --- [           main] o.s.c.c.m.FileMonitorConfiguration       : Not monitoring for local config changes
2018-04-19 19:05:26.315  INFO 67226 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2018-04-19 19:05:26.315  INFO 67226 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'rickle-1.errorChannel' has 1 subscriber(s).
2018-04-19 19:05:26.315  INFO 67226 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started _org.springframework.integration.errorLogger
2018-04-19 19:05:26.315  INFO 67226 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147482647
2018-04-19 19:05:26.315 DEBUG 67226 --- [           main] o.s.c.s.binding.BindableProxyFactory     : Binding inputs for :interface org.springframework.cloud.bus.SpringCloudBusClient
2018-04-19 19:05:26.315 DEBUG 67226 --- [           main] o.s.c.s.binding.BindableProxyFactory     : Binding :interface org.springframework.cloud.bus.SpringCloudBusClient:springCloudBusInput
2018-04-19 19:05:26.331  INFO 67226 --- [           main] c.s.b.r.p.RabbitExchangeQueueProvisioner : declaring queue for inbound: sunand.anonymous.1D6VdnJWQrqyyDVKPlvi4A, bound to: sunand
2018-04-19 19:05:26.352  INFO 67226 --- [           main] o.s.c.stream.binder.BinderErrorChannel   : Channel 'rickle-1-1.sunand.anonymous.1D6VdnJWQrqyyDVKPlvi4A.errors' has 1 subscriber(s).
2018-04-19 19:05:26.352  INFO 67226 --- [           main] o.s.c.stream.binder.BinderErrorChannel   : Channel 'rickle-1-1.sunand.anonymous.1D6VdnJWQrqyyDVKPlvi4A.errors' has 2 subscriber(s).
2018-04-19 19:05:26.370  INFO 67226 --- [           main] o.s.i.a.i.AmqpInboundChannelAdapter      : started inbound.sunand.anonymous.1D6VdnJWQrqyyDVKPlvi4A
2018-04-19 19:05:26.372  INFO 67226 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2018-04-19 19:05:26.404  INFO 67226 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8888 (http) with context path ''

**Comment by gs-spadmanabhan** [comment] 2018-04-19 14:53
Hi @spencergibb , Upon closer look at logs I found that ApplicationContext is getting refreshed at the boot up of application itself, below are the very first lines which got printed when I started the application,

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10c9374e0). One of the two will be used. Which one is undefined.
2018-04-19 20:22:20.894  INFO 85827 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@702657cc: startup date [Thu Apr 19 20:22:20 IST 2018]; root of context hierarchy
2018-04-19 20:22:21.215  INFO 85827 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$5b9c5b6e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.1.RELEASE)
```

**Comment by spencergibb** [comment] 2019-02-11 15:13
I think has been fixed in later releases, can you verify.

**Comment by spring-issuemaster** [comment] 2019-02-18 15:17
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-25 15:17
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-25 15:17 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by cristallo** [comment] 2019-04-18 08:41
Hi,
 I have the same problem and I can provide some more data. The problem seems to lie in registering the client in the broker used. Using Spring Boot 1.5.6 and Spring Cloud Dalston.SR4 a client named "client-service" with an active profile "zone1" registers on the channel 'client-service: zone1: 9181.springCloudBusInput'. This is the client log: 2019-04-17 17: 56: 30.479 INFO 3848 --- [main] osintegration.channel.DirectChannel: Channel 'client-service: zone1: 9181.springCloudBusInput' has 1 subscriber (s) .

Using Spring Boot 2.0.6 and Spring Cloud Dalston.SR4 the same client with the same profile registers on the 'client-service-1.springCloudBusInput' channel. This is the client log: 2019-04-17 17: 22: 31.028 INFO 2792 --- [main] o.s.integration.channel.DirectChannel: Channel 'client-service-1.springCloudBusInput' has 1 subscriber (s). The problem is that the Config Server continues to write the refresh on the client-service channel: zone1.
