### ISSUE TITLE
/bus/refresh took more than 40s

### ISSUE THREAD

**Issue by kratosB** [spring-cloud/spring-cloud-bus#91] opened 2017-11-07 08:18 UTC
Hi, I got problems with spring cloud bus.
I got 2 eureka servers,  2 spring cloud config servers in two machine, with about 10 clients in each server.
Every time I sent a post request( /bus/refresh ) to one of the config servers, it took 40 seconds. Is this OK? Or maybe I lost some props? Anyone cloud help me? Many thanks.

**Comment by spencergibb** [comment] 2017-11-07 15:42
No, but I also have no way of telling why. Can you provide more information, versions, logs, configuration? Maybe a project that reproduces the problem?

**Comment by kratosB** [comment] 2017-11-08 09:26
Firstly, thank you so much for reply.

My config-server was almost the same as this https://github.com/kratosB/config-service. 
There were too much clients so that I could't show you. 

The common properties for clients in application-test.yml was also in the repo.
The config-service.log in the repo was the log of the config-service (after I sent the post request "/bus/refresh")
The client-service.log in the repo was the log of one of the clients.

==============================================
2017-11-08 15:51:35.208  INFO 21753 --- [o-23006-exec-45] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6febfe2b: startup date [Wed Nov 08 15:51:35 CST 2017]; root of context hierarchy
2017-11-08 15:51:35.250  INFO 21753 --- [o-23006-exec-45] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-11-08 15:51:35.309  INFO 21753 --- [o-23006-exec-45] o.s.c.c.s.e.NativeEnvironmentRepository  : Adding property source: file:/data/tomcat_3006/temp/config-repo-8443026401158727742/mobile-service/mobile-service-dev.yml
2017-11-08 15:51:35.309  INFO 21753 --- [o-23006-exec-45] o.s.c.c.s.e.NativeEnvironmentRepository  : Adding property source: file:/data/tomcat_3006/temp/config-repo-8443026401158727742/application-test.yml
2017-11-08 15:51:35.309  INFO 21753 --- [o-23006-exec-45] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@6febfe2b: startup date [Wed Nov 08 15:51:35 CST 2017]; root of context hierarchy
=======================================================
By the way, the config-server kept in produce such logs, and I found some infomations in https://github.com/spring-cloud/spring-cloud-config/issues/423. However "spring.cloud.config.server.health.enabled=false " didn't work. According to https://github.com/spring-cloud/spring-cloud-config/pull/426, seems you guys had made health.config.enabled default to false?
Then why my server still produced these, which made me confused.
In our uat enviroment, the logs like this. Every 5-10 seconds.
=======================================================
2017-11-08 17:24:44.416  INFO 15355 --- [-23006-exec-128] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7c332a83: startup date [Wed Nov 08 17:24:44 CST 2017]; root of context hierarchy
2017-11-08 17:24:44.433  INFO 15355 --- [-23006-exec-128] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-11-08 17:24:44.472  INFO 15355 --- [-23006-exec-128] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7c332a83: startup date [Wed Nov 08 17:24:44 CST 2017]; root of context hierarchy
2017-11-08 17:24:48.383  INFO 15355 --- [-23006-exec-176] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@27989487: startup date [Wed Nov 08 17:24:48 CST 2017]; root of context hierarchy
2017-11-08 17:24:48.401  INFO 15355 --- [-23006-exec-176] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-11-08 17:24:48.451  INFO 15355 --- [-23006-exec-176] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@27989487: startup date [Wed Nov 08 17:24:48 CST 2017]; root of context hierarchy
2017-11-08 17:24:52.952  INFO 15355 --- [-23006-exec-162] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@29359235: startup date [Wed Nov 08 17:24:52 CST 2017]; root of context hierarchy
2017-11-08 17:24:52.976  INFO 15355 --- [-23006-exec-162] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-11-08 17:24:53.019  INFO 15355 --- [-23006-exec-162] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@29359235: startup date [Wed Nov 08 17:24:52 CST 2017]; root of context hierarchy
2017-11-08 17:24:58.121  INFO 15355 --- [-23006-exec-184] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@345b7634: startup date [Wed Nov 08 17:24:58 CST 2017]; root of context hierarchy
2017-11-08 17:24:58.140  INFO 15355 --- [-23006-exec-184] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-11-08 17:24:58.179  INFO 15355 --- [-23006-exec-184] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@345b7634: startup date [Wed Nov 08 17:24:58 CST 2017]; root of context hierarchy
==========================================================

**Comment by kratosB** [comment] 2017-11-10 07:56
Hi @spencergibb 

I still couldn't find any useful information to solve my problem.
Could you please take a look? Many thanks.

**Comment by spencergibb** [comment] 2018-01-18 01:44
@kratosB 
> Maybe a project that reproduces the problem?

**Comment by spencergibb** [comment] 2019-02-11 15:15
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-02-11 15:15 UTC
Labels: feedback-provided
