### ISSUE TITLE
RabbitMQ exchanges not configured correctly

### ISSUE THREAD

**Issue by JWThewes** [spring-cloud/spring-cloud-bus#55] opened 2017-02-14 14:11 UTC
When starting a "blank" RabbitMQ and launching a Spring Cloud Config Server with spring-cloud-starter-bus-amqp on the classpath the exchanges in RabbitMQ are not configured properly.
Following exchanges are created:
springCloudBusOutput
springCloudBusInput

From springCloudBusInput there's a binding for each connected Cloud Bus Client. What is missing is the binding from springCloudBusOutput to the springCloudBusInput exchange. After adding this manually everything worked.
Is this by design or a misconfiguration on my side?

**Comment by mbogoevici** [comment] 2017-02-14 14:17
@JWThewes What Spring Cloud version is this?

**Comment by JWThewes** [comment] 2017-02-14 14:20
We're on Camden.SR5
This is the relevant entry from mvn dependency:tree

org.springframework.cloud:spring-cloud-starter-bus-amqp:jar:1.2.1.RELEASE

**Comment by JWThewes** [comment] 2017-02-14 14:36
@mbogoevici Can we provide any further information? I'm really stuck right now and what's going wrong here.

**Comment by mbogoevici** [comment] 2017-02-14 14:44
@JWThewes No, thanks for the update. We'll try to figure out where the regression is coming from.

**Comment by mbogoevici** [comment] 2017-02-16 06:19
This is caused by https://github.com/spring-cloud/spring-cloud-stream/issues/810 - we will provide a fix in the next series of Spring Cloud releases. 

Closing as this is not directly caused by Spring Cloud Bus.

**Closed by mbogoevici** 2017-02-16 06:19 UTC

**Comment by ilayaperumalg** [comment] 2017-02-16 10:12
> When starting a "blank" RabbitMQ and launching a Spring Cloud Config Server with spring-cloud-starter-bus-amqp on the classpath the exchanges in RabbitMQ are not configured properly.
Following exchanges are created:
springCloudBusOutput
springCloudBusInput

I see `springCloudBusInput` and `springCloudBusOutput` are the `input` and `output` channel names for the `SpringCloudBusClient` and wondering why should these be the `exchange` names as well? Going by the default destination name, shouldn't the exchange name be `springCloudBus`?

**Comment by fkoner** [comment] 2017-04-05 22:36
The next configuration: Dalston.RC1 and Spring Boot 1.5.2.RELEASE. 

POSTing to /bus/refresh will not refresh other services (only the service on which /bus/refresh is called is refreshed).

buildscript {
	ext {
		springBootVersion = '1.5.2.RELEASE'
		gradleDockerVersion = '1.2'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		classpath("se.transmode.gradle:gradle-docker:${gradleDockerVersion}")
		classpath("io.spring.gradle:dependency-management-plugin:0.5.2.RELEASE")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'idea'
apply plugin: 'docker'
apply plugin: "io.spring.dependency-management"

version = '0.0.1'
sourceCompatibility = 1.8
targetCompatibility = 1.8

jar {
	baseName = 'ms-fake-microservice'
	version = "${project.version}"
}

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/milestone" }
	maven { url "https://repo.spring.io/snapshot" }
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter-actuator')
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.cloud:spring-cloud-starter-config')
	compile('org.springframework.cloud:spring-cloud-starter-bus-amqp')
	runtime('org.springframework.boot:spring-boot-devtools')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.RC1"
		mavenBom 'org.springframework.cloud:spring-cloud-stream-dependencies:Chelsea.RC1'
		mavenBom 'org.springframework.cloud:spring-cloud-bus:1.3.0.M1'
	}
}

group = 'microsip'

/*
docker {
	baseImage "microsip/oracle-jdk:1.8_112"
	maintainer 'Juan Francisco Alvarez Urquijo <paco@technogi.com.mx>'
}
*/

/**
 * Generic support for building docker images for SpringBoot Apps
 */
task buildDocker(type: Docker, dependsOn: build) {
	push = project.hasProperty('push')
	applicationName = rootProject.name
	dockerfile = file('src/main/docker/Dockerfile')

	doFirst {
		// Rename the app jar to "app.jar" so that the Dockerfile does not require renames
		copy {
			from "${project.buildDir}/libs"
			into stageDir
			include "${rootProject.name}-${version}.jar"
			rename("${rootProject.name}-${version}.jar", "app.jar")
		}
	}

	doLast {
		println "Run the Docker Container"
		println "docker run -ti -p 8080:8080 $project.group/$applicationName:$version"
	}
}

// @see https://github.com/spring-projects/spring-boot/issues/832
bootRun {
	systemProperties = System.properties
}
