### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by pengpan** [spring-cloud/spring-cloud-bus#82] opened 2017-08-21 09:15 UTC
I want to refresh all microservice by spring-cloud-bus. First I add spring-parent a dependency in my project's parent project, like this:
```
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-dependencies</artifactId>
   <version>Dalston.SR1</version>
   <type>pom</type>
   <scope>import</scope>
</dependency>
```
maven children project dependency  like this:
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
```
application.properties new add config : 
```
spring.rabbitmq.host: 192.168.10.59
spring.rabbitmq.port: 5672
spring.rabbitmq.username: admin
spring.rabbitmq.password: 123456
```
Introductions:  
jdk version: 1.7.0_25

OK ，Then start my application  throw  exeption
```
org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.IllegalAccessError: tried to access method org.springframework.amqp.core.ExchangeBuilder.<init>(Ljava/lang/String;Ljava/lang/String;)V from class org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at com.huize.test.config.ConfigServiceApplication.main(ConfigServiceApplication.java:20) ~[classes/:na]
Caused by: java.lang.IllegalAccessError: tried to access method org.springframework.amqp.core.ExchangeBuilder.<init>(Ljava/lang/String;Ljava/lang/String;)V from class org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner
	at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.buildExchange(RabbitExchangeQueueProvisioner.java:393) ~[spring-cloud-stream-binder-rabbit-core-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.provisionProducerDestination(RabbitExchangeQueueProvisioner.java:88) ~[spring-cloud-stream-binder-rabbit-core-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.provisionProducerDestination(RabbitExchangeQueueProvisioner.java:58) ~[spring-cloud-stream-binder-rabbit-core-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:110) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:57) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:152) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:124) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:238) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	... 14 common frames omitted

Exception in thread "Thread-4" java.lang.UnsupportedClassVersionError: org/eclipse/jgit/util/FileUtils : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.cloud.config.server.support.AbstractScmAccessor$1.run(AbstractScmAccessor.java:99)
```
I checked on the net is JDK version，spring cloud official support jdk1.7, isn't it？
Thanks!

我在项目依赖里新增 spring-cloud-starter-bus-amqp，启动就报错。晚上查了下是JDK版本原因，但是广官方不是支持JDK7吗？ 那为何还会报这个错。
麻烦谁解答下，感谢！

**Comment by spencergibb** [comment] 2017-08-21 17:58
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spencergibb** [comment] 2017-08-21 18:05
I'm unable to reproduce, will you please prepare a minimal sample that reproduces the problem?

**Comment by spencergibb** [comment] 2017-08-21 18:13
Closing in favor of https://github.com/spring-cloud/spring-cloud-config/issues/780

**Closed by spencergibb** 2017-08-21 18:13 UTC
Labels: waiting for feedback

**Comment by garyrussell** [comment] 2017-08-21 18:29
Aside from the Java 8 issue, this...

    Caused by: java.lang.IllegalAccessError: tried to access method org.springframework.amqp.core.ExchangeBuilder.<init>(Ljava/lang/String;Ljava/lang/String;)V from class org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner

...is caused by having an old version of spring-rabbit on the classpath - rabbit binder 1.2.1 should pull in spring-rabbit 1.7.2.

**Comment by pengpan** [comment] 2017-08-22 08:50
@spencergibb   Please learn how to properly format code and logs.

Don't know which didn't properly formatted, please advice and write a sample.  thanks

**Comment by pengpan** [comment] 2017-08-22 09:08
@garyrussell  
Thank you very much for your answer.
I alone upgrade spring-rabbit.jar to version  1.7.2 is still an error，but upgrade spring-boot-dependencies to version 1.5.3 (spring-rabbit auto upgrade to 1.7.2 )  then started succeeded.
Thanks again
