### ISSUE TITLE
Bus-refresh does not work with Config Server Vault

### ISSUE THREAD

**Issue by simplyi** [spring-cloud/spring-cloud-bus#191] opened 2019-04-14 13:06 UTC
Hello! 

I cannot get bus-refresh working with Spring Cloud Config Server + Vault as a backend. I feels like it is an issue with Spring Cloud Bus to me and this is why. 

I have configured Spring Cloud Config Server with Git as a backend and have enabled Spring Cloud Bus for updated properties to be pushed to my other Microservices. This configuration works and when I send HTTP Post request tp a /bus-refresh endpoint all my web services are updated with new properties. This tells me that my Spring Cloud Config Server and Spring Cloud Bus and all of my Microservices are configured properly.  

When I enable Vault as a backend in Spring Cloud Config Server I can see it can read properties stored in secret engines. I get the following response when checking if Spring Cloud Config can see the value of token.secret stored in Vault: 

```
GET http://localhost:8012/MyConfigServer/vault

{
    "name": "MyConfigServer",
    "profiles": [
        "vault"
    ],
    "label": null,
    "version": null,
    "state": null,
    "propertySources": [
        {
            "name": "vault:MyConfigServer",
            "source": {
                "token.secret": "jf9i4jg47fhdnj58yrgh35dhjf8403jdh375jf349700000"
            }
        }
    ]
}
```

The Response is successful and I can see that Spring Cloud Config can see the property stored in Vault. 

However if I try to push this value to my other Microservices subscribed to Spring Cloud Config Server, they do not get a new value. 

The following HTTP Request is Successful(HTTP Status code is 204) but Microservices are not updated. 

GET http://localhost:8012/actuator/bus-refresh

Is it an issue or there is something additional I need to configure on Spring Cloud Config Server for Spring Cloud Bus to be able to push properties to subscribed Microservices. 

If I switch to use Git as a backend then all works as expected...

**Comment by ryanjbaxter** [comment] 2019-05-15 20:33
@simplyi What version of Spring Cloud are you using?

**Comment by ryanjbaxter** [comment] 2019-05-16 13:57
I tried this using Greenwich.SR1 and it worked fine.  

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by simplyi** [comment] 2019-05-16 19:48
@ryanjbaxter Thank you for your response. I am using Greenwich.RELEASE. 

Regarding the verifiable example... I guess I need to make my Spring Cloud Config project and at least one Microservice available here on Git so that they can be cloned and ran?... They will work with Git and Native file system as a backend.. it is just the vault not working for me...

**Comment by ryanjbaxter** [comment] 2019-05-16 19:50
I guess I am more interested in seeing the client that is not working.  I can probably generate a backend that works from there.

**Comment by simplyi** [comment] 2019-05-19 22:37
@ryanjbaxter thank you! 
I have published client application here: https://github.com/simplyi/SpringCloudVideoCourse/tree/master/PhotoAppApiUsers 
and config server here: 
https://github.com/simplyi/SpringCloudVideoCourse/tree/master/PhotoAppAPIConfigServer

**Comment by aibany** [comment] 2019-07-01 04:12
Sorry, I have the same probrom in Greenwich.SR2.
My Config Server  and order-client is both:
`
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.6.RELEASE</version>
        <relativePath/>
    </parent>
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>Greenwich.SR2</spring-cloud.version>
    </properties>
`
when I update github configs，the Config Server print log:
`
2019-07-01 12:10:45.105  INFO 24262 --- [io-9999-exec-10] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2019-07-01 12:10:45.105  INFO 24262 --- [io-9999-exec-10] com.netflix.discovery.DiscoveryClient    : Application is null : false
2019-07-01 12:10:45.105  INFO 24262 --- [io-9999-exec-10] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2019-07-01 12:10:45.105  INFO 24262 --- [io-9999-exec-10] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2019-07-01 12:10:45.105  INFO 24262 --- [io-9999-exec-10] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2019-07-01 12:10:45.108  INFO 24262 --- [io-9999-exec-10] com.netflix.discovery.DiscoveryClient    : The response status is 200
2019-07-01 12:10:45.109  INFO 24262 --- [io-9999-exec-10] com.netflix.discovery.DiscoveryClient    : Starting heartbeat executor: renew interval is: 30
2019-07-01 12:10:45.109  INFO 24262 --- [io-9999-exec-10] c.n.discovery.InstanceInfoReplicator     : InstanceInfoReplicator onDemand update allowed rate per min is 4
2019-07-01 12:10:45.110  INFO 24262 --- [io-9999-exec-10] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1561954245110 with initial instances count: 2
2019-07-01 12:10:45.111  INFO 24262 --- [io-9999-exec-10] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application CONFIG-CENTER with eureka with status DOWN
2019-07-01 12:10:45.111  WARN 24262 --- [io-9999-exec-10] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1561954245111, current=DOWN, previous=STARTING]
2019-07-01 12:10:45.111  INFO 24262 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CONFIG-CENTER/30.7.60.228:config-center:9999: registering service...
2019-07-01 12:10:45.111  INFO 24262 --- [io-9999-exec-10] o.s.c.n.e.s.EurekaServiceRegistry        : Registering application CONFIG-CENTER with eureka with status UP
2019-07-01 12:10:45.111  WARN 24262 --- [io-9999-exec-10] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1561954245111, current=UP, previous=DOWN]
2019-07-01 12:10:45.111  INFO 24262 --- [io-9999-exec-10] o.s.cloud.bus.event.RefreshListener      : Received remote refresh request. Keys refreshed []
2019-07-01 12:10:45.116  INFO 24262 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CONFIG-CENTER/30.7.60.228:config-center:9999 - registration status: 204

`

the rabbitmq with order's queue can recieve msg:
`
<img width="940" alt="图片" src="https://user-images.githubusercontent.com/26923461/60410134-624ebc80-9bf9-11e9-836a-908f5a52edbd.png">

`
but the order-client has no log , and can't get configs.

**Comment by spencergibb** [comment] 2020-01-14 03:21
is this still an issue with boot 2.2.2 and Hoxton.SR1?

**Comment by isilduar** [comment] 2020-01-15 12:24
Hi @spencergibb ,

I have a similar issue with spring cloud bus and kafka. I have tried the versions of boot and cloud which you have suggested. Unfortunately nothing is happening when I push the changes to git and invoke POST request on `bus-refresh`. In logs I can see only that:
`o.s.cloud.bus.event.RefreshListener      : Received remote refresh request. Keys refreshed []`

The same issue is with cloud Greenwich.SR4 and boot 2.1.11.RELEASE.

Do you have any idea what is wrong?

**Comment by isilduar** [comment] 2020-01-16 04:56
Small update: when I invoke `bus-refresh` in one of the services value is updating according to the new config, but in other services I do not see any refresh and no message via Kafka is send to other instances. Do you have any idea what is missing?

**Comment by spring-issuemaster** [comment] 2020-04-16 01:59
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-04-23 02:00
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-04-23 02:00 UTC
Labels: feedback-reminder, waiting for feedback
