### ISSUE TITLE
How to use spring cloud bus with spring cloud vault

### ISSUE THREAD

**Issue by nithyancse** [spring-cloud/spring-cloud-bus#161] opened 2019-03-21 10:10 UTC
We are running the spring boot application(1.x) with spring cloud vault dependency. Now we have the requirement to add the spring-cloud-starter-bus-amqp in pom.xml to enable refresh event across all the micro services in single hit like/bus/refresh.
```
.............
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-vault-starter-config</artifactId>
 </dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
    <version>1.3.1.RELEASE</version>
</dependency>
.............
```
while adding the spring-cloud-starter-bus-amqp in pom.xml  we are getting the below error

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authenticationManagerImpl': Unsatisfied dependency expressed through field 'properties'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'java.util.Properties' available: expected single matching bean but found 2: integrationGlobalProperties,systemProperties
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)

```
because the spring-cloud-starter-bus-amqp dependency all ready used in spring cloud vault project. so that we are unable to put amqp dependency in pom.xml. /bus/refresh end point not exposed even though it available in effective pom.xml.

please advice here to resolve this issue

**Comment by mp911de** [comment] 2019-03-21 16:06
Please do not cross-post @nithyancse. I closed the duplicate in Spring Cloud Vault.

**Comment by ryanjbaxter** [comment] 2019-03-25 14:28
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-04-01 14:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-04-08 14:29
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-04-08 14:29 UTC
Labels: feedback-reminder, waiting for feedback
