### ISSUE TITLE
@RemoteApplicationEventScan usage alters behaviour

### ISSUE THREAD

**Issue by ugurlu** [spring-cloud/spring-cloud-bus#148] opened 2019-02-04 13:57 UTC
Hello,

spring boot: 2.1.2.RELEASE
spring-cloud: Greenwich.RELEASE

When I use following annotation in main class

```
@RemoteApplicationEventScan(basePackages = 
  { "tr.com....", "org.springframework.cloud.bus.event" })
```

```
org.springframework.messaging.converter.MappingJackson2MessageConverter
```
is instantiated before 
```
org.springframework.cloud.bus.jackson.BusJacksonAutoConfiguration
```
as a result UnknownRemotEventListener is not thrown. instead serialiazation error is thrown.

If RemoteApplicationEventScan is ommitted UnknownRemotEventListener is thrown. But since custom packages are not scanned exception is UnknownRemotEventListener for all custom events.

As a workaround I've copied BusJacksonAutoConfiguration and modified packagesToScan member then everything started work. Is there a better option? What am I missing?

**Comment by ryanjbaxter** [comment] 2019-02-04 15:53
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by ugurlu** [comment] 2019-02-08 07:59
attaching sample Comment out line 27 in ClientApp.java in order to observe behaviour

[cloud-sample.zip](https://github.com/spring-cloud/spring-cloud-bus/files/2844121/cloud-sample.zip)

**Comment by spencergibb** [comment] 2019-02-11 18:35
I'm still confused even though I have the sample.

You have two events defined in the client project, `Event` and `UnknownEvent`. Why would you not have `@RemoteApplicationEventScan(basePackages = { "org.ugurlu" })` in that project? Without it how would you expect this to work?

**Comment by ugurlu** [comment] 2019-02-12 11:58
Sorry for the confusion commenting out of RemoteApplicationEventScan should be done in ServerApp.java.

When we comment out scanning of base packages both events are captured by UnknownListener. If I enable base package scan in ServerApp Event is captured properly however instead of trigerring UnknownListener 

```
Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Could not resolve type id 'UnknownEvent' as a subtype of [simple type, class org.springframework.cloud.bus.event.RemoteApplicationEvent]: known type ids = [AckRemoteApplicationEvent, EnvironmentChangeRemoteApplicationEvent, Event, RefreshRemoteApplicationEvent, UnknownRemoteApplicationEvent]
```

exception is thrown.

**Comment by ugurlu** [comment] 2019-02-27 07:28
seems like call order MappingJackson2MessageConverter, BusJacksonAutoConfiguration changes behaviour. use of  @RemoteApplicationEventScan can cause skipping of events. Event is received from queue however is not forwarded to application

**Comment by spencergibb** [comment] 2020-01-14 03:10
RemoteApplicationEventScan shouldn't be used on spring cloud packages.

**Comment by spring-issuemaster** [comment] 2020-01-21 03:14
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-01-28 03:11
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-01-28 03:11 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by msakirc** [comment] 2020-02-03 11:05
> RemoteApplicationEventScan shouldn't be used on spring cloud packages.

I got incredibly confused here, as spring cloud documentation recommends using RemoveApplicationScan as follows:

> If you cannot or don’t want to use a subpackage of org.springframework.cloud.bus.event for your custom events, you must specify which packages to scan for events of type RemoteApplicationEvent using @RemoteApplicationEventScan. Packages specified with @RemoteApplicationEventScan include subpackages.

Can you be more specific, please?
